name: 'Label-gun'
description: 'Manage issue feedback'
author: 'Emiliano Heyns'
inputs:
  token:
    required: true
    description: 'token to post to the issue list'
  label.active:
    required: false
    description: 'only act on issues with this tag'
    default: ''
  label.exempt:
    required: false
    description: 'ignore issues with this tag'
    default: ''
  label.awaiting:
    required: true
    description: 'label issues that require user feedback to proceed'
    default: 'awaiting-user-feedback'
  label.reopened:
    required: false
    description: 're-open issue when non-collaborator posts, and label issue. Issues re-opened this way can be closed by non-collaborators'
    default: ''
  log.regex:
    required: false
    description: 'search for this regular expression to detect log ID'
    default: ''
  log.message:
    required: false
    description: 'post this comment when log ID is missing'
    default: ''
  log.label:
    required: false
    description: 'tag issues with missing log ID with this label'
    default: ''
  verbose:
    required: false
    description: 'log activity'
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: tag
