name: 'Label-gun'
description: 'Manage issue feedback'
author: 'Emiliano Heyns'
inputs:
  token:
    required: true
    description: 'token to post to the issue list'
  label.active:
    required: false
    description: 'only act on issues with this tag'
    default: ''
  label.exempt:
    required: false
    description: 'ignore issues with this tag'
    default: ''
  label.log-required:
    required: false
    description: 'tag issues with missing log ID with this label'
    default: ''
  label.awaiting:
    required: true
    description: 'follow-up prompt when log ID remains missing'
    default: 'awaiting-user-feedback'
  label.reopened:
    required: false
    description: 're-open issue when non-collaborator posts, and label issue. Issues re-opened this way can be closed by non-collaborators'
    default: ''
  log-id:
    required: false
    description: 'search for this pattern to detect log ID'
    default: ''
  message.log-required:
    required: false
    description: 'post this comment when log ID is missing'
    default: ''
  message.no-close:
    required: false
    description: 'comment to post when re-opening message closed by non-collaborator'
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: tag
