name: 'Label-gun'
description: 'Manage issue feedback'
author: 'Emiliano Heyns'
inputs:
  token:
    required: true
    description: token to post to the issue list

  label.awaiting:
    required: true
    description: label issues that require user feedback to proceed
    default: awaiting-user-feedback

  label.active:
    description: only act on issues with this tag
  label.exempt:
    description: ignore issues with this tag
  label.reopened:
    description: re-open issue when non-collaborator posts, and label issue. Issues re-opened this way can be closed by non-collaborators.

  close.message:
    description: when set, assigned issues can only be closed by collaborators. Since github doesn't allow to set this behavior, re-open the issue and show this message

  log.regex:
    description: search for this regular expression to detect log ID
  log.message:
    description: post this comment when log ID is missing
  log.label:
    description: tag issues with missing log ID with this label

  verbose:
    description: log activity

  assign:
    description: assign issue to owner on owner interaction

  issue.state:
    description: when dispatching, run for this issue state
    default: 'all'

outputs:
  issue:
    description: Issue number
  state:
    description: issue state. One of 'in-progress', 'awaiting', 'closed' or 'unmanaged'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: tag
