name: 'Label-gun'
description: 'Manage issue feedback'
author: 'Emiliano Heyns'
inputs:
  token:
    required: true
    description: token to post to the issue list

  label.awaiting:
    required: true
    description: label issues that require user feedback to proceed
    default: awaiting-user-feedback

  label.active:
    description: only act on issues with this tag
  label.exempt:
    description: ignore issues with this tag
  label.reopened:
    description: re-open issue when non-collaborator posts, and label issue. Issues re-opened this way can be closed by non-collaborators.

  close.message:
    description: when set, assigned issues can only be closed by collaborators. Since github doesn't allow to set this behavior, re-open the issue and show this message

  log.regex:
    description: search for this regular expression to detect log ID
  log.message:
    description: post this comment when log ID is missing
  log.label:
    description: tag issues with missing log ID with this label

  user.assign:
    description: assign active issues to this contributor when running the action manually
  user.bots:
    description: these user logins are actually bots

  verbose:
    description: log activity

  issue.state:
    description: when dispatching, run for this issue state
    default: 'all'

  project.url:
    description: URL of project to update
  project.token:
    description: use this token for project updates. Will use the general token if missing, but the default github action token does not have the permissions required to update projects

  project.card.status.new:
    description: project card state for open, unassigned issues
    default: 'Backlog'
  project.card.status.assigned:
    description: project card state for open, assigned issues
    default: 'In progress'
  project.card.status.awaiting:
    description: project card state for open issues awaiting user feedback
    default: 'Awaiting user input'

  project.card.field.start-date:
    description: project field to note start date
    default: 'Start date'
  project.card.field.end-date:
    description: project field to note last active date
    default: 'End date'
  project.card.field.status:
    description: project field for status
    default: 'Status'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: tag
