#!/usr/bin/env python

import subprocess
import json
import yaml
from easydict import EasyDict
import re
import pickledb
from types import SimpleNamespace

def run(cmd):
  print(' '.join(cmd))
  result = subprocess.run(cmd, check=True, capture_output=True, text=True)
  return result.stdout

def sanitize_key(key):
  key = re.sub(r'\W|^(?=\d)', '_', key)
  key = re.sub(r'_+', '_', key)
  return key

def easydict_hook(d):
  return EasyDict({sanitize_key(k): v for k, v in d.items()})

def todict(d):
  if isinstance(d, EasyDict):
    d = {k: todict(v) for k, v in d.items()}
  elif isinstance(d, list):
    d = [todict(i) for i in d]
  return d
def str_presenter(dumper, data):
  if len(data.splitlines()) > 1 or '\n' in data:  
    text_list = [line.rstrip() for line in data.splitlines()]
    fixed_data = "\n".join(text_list)
    return dumper.represent_scalar('tag:yaml.org,2002:str', fixed_data, style='|')
  return dumper.represent_scalar('tag:yaml.org,2002:str', data)
yaml.add_representer(str, str_presenter)
yaml.add_representer(EasyDict, lambda dumper, data: dumper.represent_dict(todict(data)))

###################################################
limit = '1000'
Repo = 'retorquere/zotero-better-bibtex'
Project = SimpleNamespace(number=5)
Project.name = json.loads(run(['gh', 'project', 'view', str(Project.number), '--owner', Repo.split('/')[0], '--format', 'json']), object_hook=easydict_hook).title
###################################################

result = run(['gh', 'project', 'item-list', str(Project.number), '--format', 'json', '--owner', '@me', '--limit', limit])
cards = json.loads(result, object_hook=easydict_hook).items
#for card in cards:
#  print(yaml.dump(card))

class UserTracker:
  def __init__(self):
    self.cache = pickledb.PickleDB('users.json')
    self.user = False
    self.owner = False
    self.last = None

  def ping(self, kind):
    setattr(self, kind, True)
    self.last = kind

  def issue(self, issue):
    if not self.cache.get(issue.author.login):
      if issue.author.is_bot:
        self.cache.set(issue.author.login, 'owner')
      else:
        result = run(['gh', 'api', f'repos/{Repo}/issues/{issue.number}', '--jq', '.author_association'])
        status = result.strip()
        self.cache.set(issue.author.login, 'owner' if status == 'OWNER' else 'user')
      self.cache.save()
    self.ping(self.cache.get(issue.author.login))

  def comment(self, comment):
    if not self.cache.get(comment.author.login):
      if comment.author.login == 'github-actions':
        self.cache.set(comment.author.login, 'owner')
      else:
        self.cache.set(comment.author.login, 'owner' if comment.authorAssociation == 'OWNER' else 'user')
      self.cache.save()
    self.ping(self.cache.get(comment.author.login))

result = run(['gh', 'issue', 'list', '--state', 'open', '--repo', Repo, '--json', 'assignees,author,createdAt,id,number,labels,projectItems,state,comments', '--limit', limit])
issues = json.loads(result, object_hook=easydict_hook)
print(len(issues), 'issues')
for issue in issues:
  entry = EasyDict({
    'number': issue.number,
    'repo': Repo,
    'start': issue.createdAt,
    'end': issue.createdAt,
    'status': None,
  })

  labels = [label.name for label in issue.labels]

  start_date = issue.createdAt
  end_date = issue.createdAt
  user = UserTracker()
  user.issue(issue)
  for comment in issue.comments:
    end_date = comment.createdAt
    user.comment(comment)

  card = next((c for c in cards if c.repository == Repo and c.number == issue.number), None)

  edits = []

  if user.last == 'user' and 'awaiting-user-feedback' in labels:
    edits += ['--remove-label', 'awaiting-user-feedback']
  elif user.last == 'owner' and user.user and 'awaiting-user-feedback' not in labels:
    edits == ['--add-label', 'awaiting-user-feedback']

  if user.owner and len(issue.assignees) == 0:
    edits += ['--add-assignee', 'retorquere']

  if not card:
    edits += ['--add-project', Project.name]

  if len(edits) > 0:
    run(['gh', 'issue', 'edit', f'{issue.number}', '--repo', Repo] + edits)

  if not card:
    result = run(['gh', 'project', 'item-add', str(Project.number), '--owner', Repo.split('/')[0], '--url', f'https://github.com/{Repo}/issues/{issue.number}', '--format', 'json'])
    item_id = json.loads(result, object_hook=easydict_hook).id
    card = EasyDict({ 'id': item_id, 'content': { 'repository': Repo, 'number': issue.number }, 'end_date': None, 'start_date': None, 'status': None })
    cards.append(card)

  #if issue.createdAt != card.start_date:
  #    gh project item-edit card.id --project-number str(Project.number) --owner @me --field "Start Date" --value start_date
  #if endDate != card.end_date:
  #    gh project item-edit card.id --project-number str(Project.number) --owner @me --field "End Date" --value end_date
  #if user.last == 'owner' and len([pi for pi in issue.projectItems if pi.title == Project.name and pi.status.name == 'In progress']) == 0::
  #  edits += ['--field', 'Status', '--value', 'In progress']
  print('** issue', yaml.dump(issue))
  print('** card', yaml.dump(card))
  break

