name: 'build-test'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created, edited, closed]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm start
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - uses: retorquere/label-gun@project
        with:
          token: ${{ github.token }}
          label.awaiting: awaiting-user-input
          label.reopened: reopened
          log.regex: abc-def
          log.message: please post a log ID
          log.label: log-required
          assign: retorquere
          verbose: true
          project.token: ${{ secrets.PAT }}
          project.url: https://github.com/users/retorquere/projects/5
